travis:
  secure:
    BINSTAR_TOKEN: g+CdsNf1DmDng6RVuRKrh0dI6kL+4yxdWhQbBvwkgaP99Z0GdOrYy2VS5RXL6O7VDcVq+y3TqnGvv9IzKBEfnepyDtL05YzVEOmYA7+yow7uhnkCgfOPoEm0u7NZvYtfUqJK1DK6SySA7NSW5pDTzA2jSc4sFSP0lpX3Aczh3TfqkPyTp5Tk/cdEAYUVeSThYTHvFFUpVCb82saBRVD9LWFimLPk01xYhIGn4zrKDtz+VBSxAB2eiT5f7Q94PVQ4qswWCgDjcOi5eOmNaRkGrUFB8QACoeG9dwm96duzZRrqfwr0nnR3MAxwOAkJ3lK4ovRRo07NB77Bb7N1Upj1LUQuq/KiAz2woFSdIws1yIUD6gQRKI5HdffT/lHF/ChPYEBAH2SACLrbReOTnJFjJldukpw84VYzq/bOxfRcRbalIssfIEIT6MIxqwjgB5ZX1LTPCwuhIZt4cs5wsCDDYdwNXX9MHxtZ5Ux0MM40ZU20f43E9tWOuRYPP59BEx6Xmrj8ViXyO/9JD53h5Bi29nlYr7jln97wypUGLX8WxCLK4yfiU20PGfoMM5yOWXutWtU1wzXp2GLdHvsI+MUdwVNbSLw4CaP7N+k7uSDaWjAvji1RnrZkSIuXhNhAbfg489pyJ49bL6N7JSMiiRQaZae7AhDaziTbww+7svjNEx8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
